apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-deployment
  namespace: agunuworld
  labels:
    app: sampleapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: agunuworld/java-web-app:8 
        ports:
        - containerPort: 8080

---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: sampleapp-service                  #service name varies it can be any name
  namespace: agunuworld
spec:
  type: LoadBalancer                                             #type of service and we have two types of services NodePortip and Notepod
  selector:
     app: sampleapp                                  #this selector helps to identify the label created in the pod
  ports:
  - port: 80                                                  #default
    targetPort: 8080    #target application of the pod app
    
